// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP1xhOYP5JkbGXqK99lx8EBKwRD5phZXY',
    appId: '1:240068560574:web:cb929b58e34405884080ef',
    messagingSenderId: '240068560574',
    projectId: 'meal-monkey-b12bc',
    authDomain: 'meal-monkey-b12bc.firebaseapp.com',
    storageBucket: 'meal-monkey-b12bc.firebasestorage.app',
    measurementId: 'G-CLQ42WS7FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtxuNdMZ38MWpvFERs_xDT_YPFiGByzWs',
    appId: '1:240068560574:android:3e6a3e55136b30a54080ef',
    messagingSenderId: '240068560574',
    projectId: 'meal-monkey-b12bc',
    storageBucket: 'meal-monkey-b12bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxRGn1pPqY8ZTym1aXVaA3w40kOBK-TIE',
    appId: '1:240068560574:ios:7db0bc39c65285474080ef',
    messagingSenderId: '240068560574',
    projectId: 'meal-monkey-b12bc',
    storageBucket: 'meal-monkey-b12bc.firebasestorage.app',
    iosBundleId: 'com.example.mealMonkey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxRGn1pPqY8ZTym1aXVaA3w40kOBK-TIE',
    appId: '1:240068560574:ios:7db0bc39c65285474080ef',
    messagingSenderId: '240068560574',
    projectId: 'meal-monkey-b12bc',
    storageBucket: 'meal-monkey-b12bc.firebasestorage.app',
    iosBundleId: 'com.example.mealMonkey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP1xhOYP5JkbGXqK99lx8EBKwRD5phZXY',
    appId: '1:240068560574:web:35c714a6beca2d784080ef',
    messagingSenderId: '240068560574',
    projectId: 'meal-monkey-b12bc',
    authDomain: 'meal-monkey-b12bc.firebaseapp.com',
    storageBucket: 'meal-monkey-b12bc.firebasestorage.app',
    measurementId: 'G-EQSN21KVHP',
  );
}
